### PR TITLE
change buttons

### PR DESCRIPTION
**Pull request by fracado**

### CODE REVIEW

**Comment by tanyaka** [comment]
The buttons "Add to favorites", "Move or copy", "Downloads" :

Screenshot_2024-10-10_11-13-45

should look lioke tertiary buttons in figma: 
Screenshot_2024-10-10_11-19-41

**Comment by tanyaka** [comment]
Concerning "new +" buttons, it's not consistent in design templates (right|left padding, icon vs text order). Feel free to close the conversation or adjust it after UX feedback.

**Comment by tanyaka** [comment]
Tertiary buttons should be 44px height, see figma, e.g. https://www.figma.com/design/Z7WAxbgPNfHQMwGqSLPtYB/STRUXD-92-Evaluation-of-Nextcloud-easy-storage-UI?node-id=2178-102441&t=WjgmjRT0Ggws7PCR-1
 
Screenshot_2024-10-11_14-23-55

**Comment by fracado** [comment]
> Tertiary buttons should be 44px height, see figma, e.g. https://www.figma.com/design/Z7WAxbgPNfHQMwGqSLPtYB/STRUXD-92-Evaluation-of-Nextcloud-easy-storage-UI?node-id=2178-102441&t=WjgmjRT0Ggws7PCR-1
> 
> Screenshot_2024-10-11_14-23-55

Vedran confirmed in chat that all buttons should have a height of 36px, including tertiary.

**Review by tanyaka — APPROVED** [review]
Review OK

**Pull request merged**
